## Numpy Refresher

If you are new to `numpy`, first go through the following [tutorial](https://numpy.org/devdocs/user/quickstart.html). 

Once completed, solve the exercises, below. If you feel confident with `numpy`, you can skip these exercises.

### Exercise 1: Importing NumPy

**Task**: Import the numpy library and give it the alias "np".

**Solution**:

In [1]:
import numpy as np

### Exercise 2: Creating Arrays

**Task**: Create a numpy array of integers from 1 to 10.

**Solution**:

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


### Exercise 3: Reshaping Arrays

**Task**: Convert the previously created array into a 2x5 matrix.

**Solution**:

In [3]:
matrix = arr.reshape(2, 5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Exercise 4: Basic Array Operations

**Task**: Compute the sum, mean, and standard deviation of the elements in the matrix.

**Solution**:

In [4]:
sum_val = np.sum(matrix)
mean_val = np.mean(matrix)
std_dev = np.std(matrix)
print("Sum:", sum_val, "Mean:", mean_val, "Standard Deviation:", std_dev)

Sum: 55 Mean: 5.5 Standard Deviation: 2.8722813232690143


### Exercise 5: Array Indexing

**Task**: From the matrix, extract the value at the 2nd row and 3rd column.

**Solution**:

In [6]:
value = matrix[1, 2]
print(value)

8


### Exercise 6: Slicing

**Task**: Extract the first row from the matrix.

**Solution**:

In [5]:
first_row = matrix[0, :]
print(first_row)

[1 2 3 4 5]


### Exercise 7: Element-wise Operations

**Task**: Multiply every element of the matrix by 2.

**Solution**:

In [6]:
doubled_matrix = matrix * 2
print(doubled_matrix)

[[ 2  4  6  8 10]
 [12 14 16 18 20]]



### Exercise 8: Matrix Multiplication

**Task**: Multiply the matrix with its transpose.

**Solution**:

In [7]:
result = np.dot(matrix, matrix.T)
print(result)

[[ 55 130]
 [130 330]]


### Exercise 9: Boolean Indexing

**Task**: From the array created in Exercise 2, extract all even numbers using boolean indexing.

**Solution**:

In [8]:
even_numbers = arr[arr % 2 == 0]
print(even_numbers)

[ 2  4  6  8 10]


### Exercise 10: Zero and Ones

**Task**: Create a 3x3 matrix full of zeros and a 4x4 matrix full of ones.

**Solution**:

In [9]:
zeros_matrix = np.zeros((3, 3))
ones_matrix = np.ones((4, 4))
print(zeros_matrix)
print(ones_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Exercise 11: Range and Reshape

**Task**: Create an array of numbers from 20 to 40 and reshape it into a 3x7 matrix.

**Solution**:

In [10]:
range_arr = np.arange(20, 41).reshape(3, 7)
print(range_arr)

[[20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33]
 [34 35 36 37 38 39 40]]


### Exercise 12: Random Numbers

**Task**: Generate a 5x2 matrix of random numbers between 0 and 1.

**Solution**:

In [11]:
random_matrix = np.random.rand(5, 2)
print(random_matrix)

[[5.30656577e-01 2.60006481e-01]
 [6.33300897e-01 7.66553525e-01]
 [6.10849680e-01 2.24133484e-01]
 [8.04698950e-01 4.65583451e-04]
 [1.52822235e-01 2.01695284e-01]]


### Exercise 13: Max and Min

**Task**: Find the maximum and minimum value of the matrix created in Exercise 12.

**Solution**:

In [12]:
max_val = np.max(random_matrix)
min_val = np.min(random_matrix)
print("Max:", max_val, "Min:", min_val)

Max: 0.8046989496110076 Min: 0.00046558345131653134


### Exercise 14: Broadcasting

**Task**: Add the matrix `[1, 2]` to each row of the matrix created in Exercise 12.

**Solution**:

In [13]:
broadcasted_matrix = random_matrix + np.array([1, 2])
print(broadcasted_matrix)

[[1.53065658 2.26000648]
 [1.6333009  2.76655353]
 [1.61084968 2.22413348]
 [1.80469895 2.00046558]
 [1.15282224 2.20169528]]



### Exercise 15: Linear Spaces

**Task**: Create an array of 50 evenly spaced points between 0 and 10.

**Solution**:

In [14]:
lin_space = np.linspace(0, 10, 50)
print(lin_space)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


### Exercise 16: Element-wise Comparison

**Task**: Compare the matrix created in Exercise 12 with a threshold of 0.5. If an element is greater than 0.5, it should be labeled as `True`, otherwise `False`.

**Solution**:


In [15]:
compared_matrix = random_matrix > 0.5
print(compared_matrix)

[[ True False]
 [ True  True]
 [ True False]
 [ True False]
 [False False]]


### Exercise 17: Dot Product

**Task**: Given two vectors `A = [2, 3]` and `B = [4, 5]`, compute their dot product.

**Solution**:

In [17]:
A = np.array([2, 3])
B = np.array([4, 5])
dot_product = np.dot(A, B)
print(dot_product)

23


### Exercise 18: Matrix-vector Multiplication

**Task**: Multiply matrix `M = [[1, 2], [3, 4]]` with vector `V = [5, 6]`.

**Solution**:

In [18]:
M = np.array([[1, 2], [3, 4]])
V = np.array([5, 6])
result = np.dot(M, V)
print(result)

[17 39]


### Exercise 19: Matrix-matrix Multiplication

**Task**: Multiply matrix `X = [[1, 2], [3, 4]]` with matrix `Y = [[2, 0], [1, 3]]`.

**Solution**:

In [19]:
X = np.array([[1, 2], [3, 4]])
Y = np.array([[2, 0], [1, 3]])
result = np.dot(X, Y)
print(result)

[[ 4  6]
 [10 12]]


### Exercise 20: Outer Product

**Task**: Compute the outer product of vectors `A = [2, 3]` and `B = [4, 5]`.

**Solution**:

In [20]:
outer_product = np.outer(A, B)
print(outer_product)

[[ 8 10]
 [12 15]]


### Exercise 21: Matrix-vector Product Using @ Operator

**Task**: Multiply matrix `M = [[1, 2], [3, 4]]` with vector `V = [5, 6]` using the `@` operator.

**Solution**:

In [21]:
result = M @ V
print(result)

[17 39]



### Exercise 22: Kronecker Product

**Task**: Compute the Kronecker product of matrices `X = [[1, 2], [3, 4]]` and `Y = [[0, 5], [6, 7]]`.

**Solution**:

In [22]:
kronecker_product = np.kron(X, Y)
print(kronecker_product)

[[ 2  0  4  0]
 [ 1  3  2  6]
 [ 6  0  8  0]
 [ 3  9  4 12]]


### Exercise 23: Element-wise Multiplication

**Task**: Perform an element-wise multiplication of matrices `A = [[2, 3], [4, 5]]` and `B = [[1, 0], [0, 1]]`.

**Solution**:

In [23]:
A = np.array([[2, 3], [4, 5]])
B = np.array([[1, 0], [0, 1]])
elementwise_product = A * B
print(elementwise_product)

[[2 0]
 [0 5]]


### Exercise 24: Cross Product

**Task**: Compute the cross product of vectors `P = [1, 2, 3]` and `Q = [4, 5, 6]`.

**Solution**:

In [24]:
P = np.array([1, 2, 3])
Q = np.array([4, 5, 6])
cross_product = np.cross(P, Q)
print(cross_product)

[-3  6 -3]
